version: "3.5"

services:
  # TODO: setup docker
  # app:
  #   image: eriksencosta/php-dev
  #   volumes:
  #     - .:/var/www
  #   ports:
  #     - "8080:80"
  #   links:
  #     - db:mysql
  #   depends_on: 
  #     - db

  db:
    image: mysql:latest
    volumes:
      - ./docker/db/orion-db.sql:/docker-entrypoint-initdb.d/orion-db.sql:cached
    ports:
      - "8081:3306"
    environment:
      - MYSQL_DATABASE=oriondb
      - MYSQL_USER=orionuser
      - MYSQL_PASSWORD=orionuserpass
      - MYSQL_ROOT_PASSWORD=ChangeMeIfYouWant

